version: "3.7"
services:
  db-caca-bugs:
    image: mysql:5.7
    container_name: caca_bugs_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: opECcbQ^tF!EA
      MYSQL_DATABASE: caca_bugs
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - caca_bugs_default
  app-caca-bugs:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: https://telemidia-ma.com.br/caca_bugs
    container_name: caca_bugs
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: caca_bugs
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: opECcbQ^tF!EA
      MYSQL_ROOT_PASSWORD: opECcbQ^tF!EA
    ports:
      - 5100:80
      - 5101:8081
    networks:
      - caca_bugs_default
volumes:
  database-data:
networks:
  caca_bugs_default:
