version: "3.7"
services:
  db-caca-bugs:
    image: mysql:5.7
    container_name: caca_bugs_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: opECcbQ^tF!EA
      MYSQL_DATABASE: caca_bugs
    volumes:
      - database-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - caca_bugs_default
  app-caca-bugs:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: caca_bugs
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: caca_bugs
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: opECcbQ^tF!EA
      MYSQL_ROOT_PASSWORD: opECcbQ^tF!EA
    ports:
      - 5100:80
      - 5101:8081
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'caca_bugs_phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 
      MYSQL_ROOT_PASSWORD: opECcbQ^tF!EA
      MYSQL_USER: root
      MYSQL_PASSWORD: opECcbQ^tF!EA
    ports:
      - 51200:80  
    networks:
      - caca_bugs_default
volumes:
  database-data:
networks:
  caca_bugs_default:
